// BIP-39 parity gate: the Kotlin Bip39 port must reproduce, byte-for-byte,
// the mnemonics and master seeds the iOS BIP39.swift produces. Vectors in
// src/test/resources/bip39.kat.json are generated by compiling the ACTUAL
// iOS BIP39.swift + PBKDF2.swift (elabify-core/tools/bip39_oracle),
// so a green test means an Android-derived holder identity equals the iOS
// one for the same 24 words + passphrase.

package com.elabify.core

import org.json.JSONObject
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class Bip39KatTest {

    @Test
    fun matchesIosOracle() {
        val stream = javaClass.getResourceAsStream("/bip39.kat.json")
            ?: error("bip39.kat.json not found on the test classpath")
        val body = JSONObject(stream.bufferedReader(Charsets.UTF_8).readText())
        val vectors = body.getJSONArray("vectors")
        assertTrue(vectors.length() > 0, "bip39 corpus is empty")

        for (i in 0 until vectors.length()) {
            val v = vectors.getJSONObject(i)
            val entropyHex = v.getString("entropyHex")
            val mnemonic = v.getString("mnemonic")
            val passphrase = v.getString("passphrase")
            val bip39SeedHex = v.getString("bip39SeedHex")
            val masterSeedHex = v.getString("masterSeedHex")

            val entropy = hexToBytes(entropyHex)
            val words = Bip39.mnemonicFromEntropy(entropy)
            assertEquals(mnemonic, words.joinToString(" "), "mnemonic[$i] ($entropyHex)")

            // Decode round-trip + checksum validation.
            assertEquals(
                entropyHex,
                bytesToHex(Bip39.entropyFromMnemonic(words)),
                "entropy round-trip[$i]",
            )

            assertEquals(
                bip39SeedHex,
                bytesToHex(Bip39.derivedSeed(words, passphrase)),
                "bip39 seed[$i] (passphrase='$passphrase')",
            )
            assertEquals(
                masterSeedHex,
                bytesToHex(Bip39.masterSeed(words, passphrase)),
                "master seed[$i] (passphrase='$passphrase')",
            )
        }
    }
}
